#!/bin/bash
echo -e "Please provide filename you want to create: \c"
read -r file
touch script/$file.c
echo '#include <stdio.h>' > script/$file.c
echo '' >> script/$file.c
echo 'int main()' >> script/$file.c
echo '{' >> script/$file.c
echo '	printf();' >> script/$file.c
echo '	return 0;' >> script/$file.c
echo '}' >> script/$file.c
